import express from 'express';
import helmet from 'helmet';
import authRouter from './routes/authRoutes.js';
import { errorHandler, notFoundHandler } from './middleware/errorHandler.js';
export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(express.json({ limit: '10kb' }));
app.get('/health', (request, response) => response.status(200).json({ status: 'ok' }));
app.use('/api/auth', authRouter);
app.use(notFoundHandler);
app.use(errorHandler);
